### ISSUE TITLE
Use of ike-vendor-ids in other (open-source) softwares

### ISSUE THREAD

**Issue by p-l-** [royhills/ike-scan#19]
Hi, I plan to use the `ike-vendor-ids` file in a new feature of [IVRE](/cea-sec/ivre) to identify ISAKMP banners collected from Masscan.

Knowing that IVRE is open-source (GPLv3+), would that be a problem for you?

Also, I'm not sure yet whether I would like to ship a copy of the file with the project source code. If I would like to, would that be a problem for you?

Thanks!

**Comment by royhills** [comment]
I'm OK with your proposed use.  I'm happy that you find it useful.

I suspect the GPLv3 license gives you the right to do this anyway, but thanks for asking.

Roy

**Comment by p-l-** [comment]
Thanks a lot for your answer!

**Comment by Thermi** [comment]
Will you give consent to using parts of the file in a GPLv2/MIT licensed project?
