### ISSUE TITLE
the tar file does not contain configure 

### ISSUE THREAD

**Issue by wefa** [royhills/ike-scan#31]
The tar file does not contain configure and can therefore not be built as described in README.

**Comment by royhills** [comment]
Where is the tar file coming from?  The ike-scan git repo shouldn't contain a tar file, and it doesn't contain "configure" either as that's a generated file.  The README should say this about installing.  The "autoreconf --install" bit generates "configure":

ike-scan uses the standard GNU autoconf and automake tools, so installation is the normal process:

    Run git clone https://github.com/royhills/ike-scan.git to obtain the project source code
    Run cd ike-scan to enter source directory
    Run autoreconf --install to generate a viable ./configure file
    Run ./configure or ./configure --with-openssl to use the OpenSSL libraries
    Run make to build the project
    Run make check to verify that everything works as expected
    Run make install to install (you'll need root or sudo for this part)
